server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/booking"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "maixuanhieu250123@gmail.com"
    password: "zmfd aycm rzuu oarb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # servlet:
    # multipart:
      # max-file-size: 10MB
      # max-request-size: 10MB

# api:
  # prefix: api/v1

jwt:
  signerKey: "WUDIpBC14uxAzco8EZo8Llkuz1l1Q05IXnYBv7mOZLrrlJVWvK/ytCDoak0OdkgL"