server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/booking"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # servlet:
    # multipart:
      # max-file-size: 10MB
      # max-request-size: 10MB

# api:
  # prefix: api/v1