version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: booking_es
    environment:
      - node.name=booking_es
      - cluster.name=booking-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_booking_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: booking_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_booking_data:
    driver: local